#!/bin/bash
set -e
set -x

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -z "$BATCH_RUN" ]; then
    make -C $DIR jar
fi

VERSION=$(grep version $DIR/build.sbt | sed 's/^version.*\"\(.*\)\"\r/\1/')

java -jar target/scala-2.13/semantic-graph.scala-assembly-$VERSION.jar ${@:1}