#!/bin/bash
set -e
set -x

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -z "$BATCH_RUN" ]; then
    make -C $DIR jar
fi

VERSION=$(grep version $DIR/build.sbt | sed 's/^version.*\"\(.*\)\"\r/\1/')

JAR=target/scala-2.13/semantic-graph.scala-assembly-$VERSION.jar

gitver=$(cat $JAR.gitver)
echo "Running SemanticGraph (Git hash: $gitver)"

java -jar $JAR ${@:1}