#!/bin/bash
set -e
set -x

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -z "$BATCH_RUN" ]; then
    make -C $DIR jar
fi

java -jar target/scala-2.13/semantic-graph.scala-assembly-0.2.0.jar ${@:1}